engines:
    phpmd:
        enabled: true
        config:
            file_extensions: "php"

    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"

    duplication:
        enabled: true
        config:
            languages:
                - php:

ratings:
    paths:
        - "src/Questions"
        - "src/Home"
        - "src/Tags"
        - "src/User"

exclude_paths:
    - "test/**"
    - "vendor/**"
    - "src/Page"
    - "src/Navigation"
    - "src/StyleChooser"
